spring.application.name=finance-tracker

# Database config with environment variables fallback
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/finance_tracker}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# JWT Security
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=86400000

# Telegram Bot
telegram.bot.username=financewithbekabot
telegram.bot.token=${TELEGRAM_BOT_TOKEN}

# Logging
logging.level.org.springframework.aop.framework.CglibAopProxy=ERROR
